### PR TITLE
Added forbidden dimensions config

### PR DESCRIPTION
**Pull request by Ugachaga**
https://github.com/runescapejon/Minecraft-Backpack-Mod/issues/2

### CODE REVIEW

**Comment by Ugachaga** [comment]
bump
@runescapejon can we get new version? or is there any issues?

**Comment by runescapejon** [comment]
oo sorry dude i was away for while

**Comment by Ugachaga** [comment]
Could you compile and post release? I have no dev environment here.

**Comment by runescapejon** [comment]
done ^

**Pull request merged**
